@baseUrl = http://localhost:3000
@boardId = board:bf4d1104-14b2-4ae2-8d11-74abca7d0422
@listId = list:bdf46a5f-1bfa-49be-b7d3-9d9bc1a8e043


### Get lists for a board
GET {{baseUrl}}/api/boards/{{boardId}}/lists

### Create list
POST {{baseUrl}}/api/boards/{{boardId}}/lists

{
  "title": "Todo"
}

### Update list
PUT {{baseUrl}}/api/boards/{{boardId}}/lists/{{listId}}

{
  "title": "In Progress",
  "color": "#ffcc00"
}

### Delete list
DELETE {{baseUrl}}/api/boards/{{boardId}}/lists/{{listId}}